services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventify_front_end
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL= ${VITE_BACKEND_URL}
    volumes:
      - .:/app:cached
    command: ["npm", "run", "dev"]